### ISSUE TITLE
Site is dead.

### ISSUE THREAD

**Issue by FroGPipA** [izolenta/sherlock#2]
Solution!!!!!

I have prepared Docker image with game for individual deployment.

Search **acherkashin1983/sherlock-game** on Docker HUB.

or 

**docker run --name Sherlock -p 8080:80 -d acherkashin1983/sherlock-game**

**Comment by izolenta** [comment]
@FroGPipA this repo is obsolete, but the game is still alive at https://sherlock.sharov.io/
